(with-eval-after-load 'diminish
  (diminish 'company-mode)
  (diminish 'company-box-mode)
  (diminish 'anzu-mode)
  (diminish 'hl-line-mode)
  (diminish 'hi-lock-mode)
  (diminish 'highlight-parentheses-mode)
  (diminish 'super-save-mode)
  (diminish 'eldoc-mode)
  (diminish 'gcmh-mode)
  (diminish 'which-key-mode)
  (diminish 'projectile-mode)
  (diminish 'color-outline-mode)
  (diminish 'all-the-icons-dired-mode)
  (diminish 'dired-omit-mode)
  (diminish 'subword-mode)
  (diminish 'sqlind-minor-mode)
  (diminish 'buffer-face-mode)
  (diminish 'org-indent-mode)
  (diminish 'org-edit-latex-mode)
  (diminish 'org-fancy-priorities-mode)
  (diminish 'visual-line-mode)
  )

(provide 'weiss_diminish_settings)
