(define-prefix-command 'wks-leader-keymap)

(wks-define-key
 wks-leader-keymap  ""
 '((", e" .  weiss-execute-buffer)
   (", c" .  quickrun-compile-only)
   (", s" .  weiss-run-java-spring)
   (", d" .  eval-defun)
   (", m" .  weiss-eval-last-sexp-this-line)
   (", f" .  eval-expression)
   (", r" .  eval-region)
   (", x" .  save-buffers-kill-terminal)
   (", 5" .  revert-buffer)

   (". p" .  narrow-to-page)
   (". x" .  widen)
   (". r" .  narrow-to-region)
   (". d" .  narrow-to-defun)

   ("-" . xah-cycle-hyphen-underscore-space)
   ("_" . weiss-insert-underscore)
   (";" . save-buffer)
   ("`" . delete-window)
   ("S-<dead-grave>" . delete-window)
   ("=" . split-window-right)
   ("5" . weiss-refresh)
   ;; ("9" . (weiss-copy-whole-buffer (kill-new (buffer-substring))))

   ("a" . weiss-split-window-dwim)

   ("b a" . mark-whole-buffer)
   ("b c" . weiss-copy-whole-buffer)
   ("b k" . (weiss-kill-whole-buffer (kill-region (point-min) (point-max))))
   ("b x" . (weiss-comment-whole-buffer (comment-or-uncomment-region
                                         (point-min)  (point-max))))
   ("b d" . (weiss-delete-whole-buffer (delete-region (point-min) (point-max))))
   ("b e" . (weiss-paste-whole-buffer
             (progn
               (weiss-delete-whole-buffer)
               (yank)
               ) ))

   ("c a" . weiss-kill-append)
   ("c b" . weiss-copy-whole-buffer)
   ("c e" . weiss-exchange-region-kill-ring-car)
   ("c f" . (weiss-copy-file-name (kill-new (buffer-file-name))))
   ("c k" . save-buffers-kill-terminal)
   ("c p" . xah-copy-file-path)
   ("c h" . xah-show-kill-ring)
   ("c SPC" . weiss-kill-append-with-space)
   ("c RET" . weiss-kill-append-with-newline)
   ("c ," . weiss-kill-append-with-comma)
   ("c l" . weiss-kill-append-with-pipe)
   ("c r" . xah-copy-to-register-1)
   ("c v" . xah-paste-from-register-1)


   ("d b" .  weiss-save-current-content)
   ;; ("d d" .  weiss-switch-and-bookmarks-search)
   ("d l" .  list-buffers)
   ("d m" .  magit-status)
   ("d n" .  weiss-new-temp-file)
   ("d o" .  xah-open-file-at-cursor)

   ("d w" .  xah-open-in-external-app)

   ("e b" .  org-babel-tangle)
   ("e c" .  org-capture)
   ("e -" .  weiss-add-dashs)

   ("f" . execute-extended-command)
   ("g" . kill-line)
   ("h" . beginning-of-buffer)

   ("i d" .  weiss-insert-date)
   ("i e" .  find-file)
   ("i v" .  yank-pop)
   ("i m s" .  all-the-icons-insert)
   ("i i" .  imenu)


   ("j K" .  Info-goto-emacs-key-command-node)
   ("j a" .  apropos-command)
   ("j b" .  describe-bindings)
   ("j c" .  describe-char)
   ("j d" .  apropos-documentation)
   ("j e" .  view-echo-area-messages)
   ("j f" .  describe-function)
   ("j g" .  info-lookup-symbol)
   ("j h" .  describe-face)
   ("j i" .  info)
   ("j j" .  man)
   ("j k" .  describe-key)
   ("j l" .  view-lossage)
   ("j m" .  describe-mode)
   ("j n" .  apropos-value)
   ("j o" .  describe-language-environment)
   ("j p" .  finder-by-keyword)
   ("j r" .  apropos-variable)
   ("j s" .  describe-syntax)
   ("j u" .  elisp-index-search)
   ("j v" .  describe-variable)
   ("j x" .  describe-coding-system)
   ("j z" .  Info-goto-emacs-command-node)

   ("TAB" . indent-rigidly)

   ("k SPC" .  xah-clean-whitespace)
   ("k TAB" . align-regexp)
   ("k -" .  xah-cycle-hyphen-underscore-space)
   ("k 1" .  xah-append-to-register-1)
   ("k 2" .  xah-clear-register-1)
   ("k 3" .  xah-copy-to-register-1)
   ("k $" .  xah-copy-to-register-1)
   ("k 4" .  xah-paste-from-register-1)
   ("k DEL" .  xah-paste-from-register-1)
   ("k 8" .  xah-clear-register-1)
   ("k 7" .  xah-append-to-register-1)
   ("k 0" .  sort-numeric-fields)
   ("k S" .  reverse-region)
   ("k c" .  move-to-column)
   ("k d" .  delete-non-matching-lines)
   ("k e" .  list-matching-lines)
   ("k f" .  delete-frame)
   ("k i" .  weiss-indent)
   ("k j" .  kill-current-buffer)
   ("k l" .  goto-line)
   ("k m" .  xah-make-backup-and-save)
   ("k n" .  repeat-complex-command)
   ("k N" .  sort-numeric-fields)
   ("k q" .  xah-reformat-lines)
   ("k r" .  anzu-query-replace-regexp)
   ("k s" .  sort-lines)
   ("k S" .  sort-fields)
   ("k t" .  repeat)
   ("k u" .  delete-matching-lines)
   ("k w" .  delete-window)
   ("k y" .  delete-duplicate-lines)

   ("l SPC" .  whitespace-mode)
   ("l ." . toggle-frame-fullscreen)
   ("l 0" . shell-command-on-region)
   ("l C" .  toggle-case-fold-search)
   ("l b" .  toggle-debug-on-error)
   ("l c" .  dired-collapse-mode)
   ("l e" .  eshell)
   ("l h" .  weiss-toggle-hl-line)
   ("l t" .  toggle-truncate-lines)
   ("l l" .  highlight-symbol)             ;wrap-line
   ("l m" .  shell-command)
   ("l n" .  display-line-numbers-mode)
   ("l r" .  dired-toggle-read-only)
   ("l s" .  sudo-edit)
   ("l w" .  toggle-word-wrap)

   ("m" . dired-jump)
   ("n" . end-of-buffer)

   ("o t" .  telega)
   ("o v" . yank-rectangle)
   ("o s" . weiss-start-kmacro)
   ("o l" . weiss-kmacro-insert-letter)
   ("o k" . weiss-deactivate-mark)
   ("o p" .
    (weiss-open-studien-plan
     (find-file "~/Documents/Org-roam/ƦProject-studienplan_2021032320.org")))
   ("o e" . weiss-end-kmacro)
   ("o c" . kmacro-call-macro)

   ("p" .
    (weiss-insert-line-and-goto-insert-mode
     (weiss-insert-line)
     (wks-vanilla-mode-enable)))
   ("q" . xah-fill-or-unfill)
   ("r" . anzu-query-replace)

   ("s c" . flyspell-auto-correct-word)
   ("s s" . weiss-flyspell-save-word)
   ;; ("s r" . weiss-wucuo-spell-check-visible-region)
   ("s g" . wucuo-start)



   ;; ("u" . isearch-forward)

   ("w f" .  xref-find-definitions)
   ;; ("w m" .  list-bookmarks)
   ("w n" .  weiss-new-frame)
   ("w t" .  weiss-test)
   ("w l" .  xref-pop-marker-stack)
   ("w u" .  winner-undo)                  ;windows setting
   ("w r" .  winner-redo)
   ("w o" .  org-babel-tangle-jump-to-org)

   ("x s" . weiss-save-all-buffers))
 )

(provide 'weiss_wks_leader)
