(define-prefix-command 'wks-leader-keymap)

(wks-define-key
 wks-leader-keymap  ""
 '((", e" .  weiss-execute-buffer)
   (", c" .  quickrun-compile-only)
   (", s" .  weiss-run-java-spring)
   (", d" .  eval-defun)
   (", m" .  weiss-eval-last-sexp-this-line)
   (", f" .  eval-expression)
   (", r" .  eval-region)
   (", x" .  save-buffers-kill-terminal)
   (", 5" .  revert-buffer)

   (". p" .  narrow-to-page)
   (". x" .  widen)
   (". r" .  narrow-to-region)
   (". d" .  narrow-to-defun)
   
   ("_" . weiss-insert-underscore)
   (";" . save-buffer)
   ("`" . delete-window)
   ("S-<dead-grave>" . delete-window)
   ("=" . split-window-right)
   ("5" . weiss-refresh)
   ;; ("9" . (weiss-copy-whole-buffer (kill-new (buffer-substring))))

   ("a" . weiss-split-window-dwim)

   ("b a" . mark-whole-buffer)
   ("b b" . weiss-save-current-content)
   ("b c" . weiss-copy-whole-buffer)
   ("b d" . (weiss-delete-whole-buffer (delete-region (point-min) (point-max))))
   ("b e" . (weiss-paste-whole-buffer (progn (weiss-delete-whole-buffer) (yank))))
   ("b k" . (weiss-kill-whole-buffer (kill-region (point-min) (point-max))))
   ("b l" . list-buffers)
   ("b x" . (weiss-comment-whole-buffer (comment-or-uncomment-region (point-min)  (point-max))))

   ("c a" . weiss-kill-append-with-and)
   ("c b" . weiss-copy-whole-buffer)
   ("c e" . weiss-exchange-region-kill-ring-car)
   ("c f" . (weiss-copy-file-name (kill-new (buffer-file-name))))
   ("c k" . save-buffers-kill-emacs)
   ("c p" . xah-copy-file-path)
   ("c h" . xah-show-kill-ring)
   ("c SPC" . weiss-kill-append-with-space)
   ("c RET" . weiss-kill-append-with-newline)
   ("c ," . weiss-kill-append-with-comma)
   ("c ." . weiss-kill-append-with-dot)
   ("c l" . weiss-kill-append-with-pipe)
   ("c r" . xah-copy-to-register-1)
   ("c v" . xah-paste-from-register-1)
   
   ("d m" .  magit-status)
   ("d n" .  weiss-new-chat-file)
   
   ;; ("f" . execute-extended-command)
   ;; ("g" . kill-line)
   ("h" . beginning-of-buffer)

   ("i d" .  weiss-insert-date)
   ("i w" .  weiss-insert-week)
   ("i e" .  find-file)
   ("i v" .  yank-pop)
   ("i m e" . emoji-insert)
   ("i i" .  imenu)


   ("j K" .  Info-goto-emacs-key-command-node)
   ("j a" .  apropos-command)
   ("j b" .  describe-bindings)
   ("j c" .  describe-char)
   ("j d" .  apropos-documentation)
   ("j e" .  view-echo-area-messages)
   ("j f" .  describe-function)
   ("j g" .  info-lookup-symbol)
   ("j h" .  describe-face)
   ("j i" .  info)
   ("j j" .  man)
   ("j k" .  describe-key)
   ("j l" .  view-lossage)
   ("j m" .  describe-mode)
   ("j n" .  apropos-value)
   ("j o" .  describe-language-environment)
   ("j p" .  finder-by-keyword)
   ("j r" .  apropos-variable)
   ("j s" .  describe-syntax)
   ("j u" .  elisp-index-search)
   ("j v" .  describe-variable)
   ("j x" .  describe-coding-system)
   ("j z" .  Info-goto-emacs-command-node)

   ("TAB" . indent-rigidly)

   ("k N" .  sort-numeric-fields)
   ("k S" .  reverse-region)
   ("k S" .  sort-fields)
   ("k TAB" . align-regexp)
   ("k d" .  delete-non-matching-lines)
   ("k f" .  delete-frame)
   ("k c" .  move-to-column)
   ("k s" .  sort-lines)
   ("k w" .  delete-window)
   ("k x" .  kill-current-buffer)
   ("k y" .  delete-duplicate-lines)
   ("k SPC" .  xah-clean-whitespace)

   ("l SPC" .  whitespace-mode)
   ("l ." . toggle-frame-fullscreen)
   ("l C" .  toggle-case-fold-search)
   ("l b" .  toggle-debug-on-error)
   ("l c" .  dired-collapse-mode)
   ("l e" .  eshell)
   ("l h" .  weiss-toggle-hl-line)
   ("l t" .  toggle-truncate-lines)
   ("l n" .  display-line-numbers-mode)
   ("l r" .  dired-toggle-read-only)
   ("l s" .  sudo-edit)
   ("l w" .  toggle-word-wrap)

   ("m" . dired-jump)
   ("n" . end-of-buffer)

   ("o t" .  telega)
   ("o s" . weiss-start-kmacro)
   ("o l" . weiss-kmacro-insert-letter)
   ("o k" . weiss-deactivate-mark)
   ("o e" . weiss-end-kmacro)
   ("o c" . kmacro-call-macro)

   ("p" .
    (weiss-insert-line-and-goto-insert-mode
     (weiss-insert-line)
     (wks-vanilla-mode-enable)))
   ("q" . xah-fill-or-unfill)
   ("r" . anzu-query-replace)

   ;; ("s c" . flyspell-auto-correct-word)
   ;; ("s s" . weiss-flyspell-save-word)
   ;; ("s r" . weiss-wucuo-spell-check-visible-region)
   ;; ("s g" . wucuo-start)



   ;; ("u" . isearch-forward)
   
   ("w n" .  weiss-new-frame)
   ("w t" .  weiss-test)
   ("w u" .  winner-undo)                  ;windows setting
   ("w r" .  winner-redo)
   
   ("x s" . weiss-save-all-buffers))
 )

(provide 'weiss_wks_leader)
