(with-eval-after-load 'rotate-text
  (setq rotate-text-words
        '(("true" "false")
          ("nil" "t")
          ("yes" "no")
          ("car" "cdr")
          ("add" "remove")
          ("width" "height")
          ("left" "right")
          ("top" "bottom")                            
          ("Background" "Foreground")
          ("background" "foreground")
          ("next" "previous")
          ("beginning" "end")
          ("below" "above")
          ("up" "down")
          ("Up" "Down")
          ("forward" "backward")
          ("downward" "upward")
          ("expand" "contract")
          ("enable" "disable")
          ("increase" "decrease")
          ("shrink" "enlarge")
          ("copy" "yank")
          ("show" "hide")
          ("start" "end")
          ("min" "max")
          ("on" "off")
          ("ON" "OFF")
          ("when" "unless")
          ("from" "to")
          ("even" "odd")
          ("columns" "rows")
          ("after" "before")
          ;; Germany Language
          ("der" "das" "die")
          ))
  )

;; parent: 
(provide 'weiss_rotate-text_settings)
