;; file-bookmark

;;; Require
(require 'snails-core)
(require 'bookmark)

;;; Code:
(snails-create-sync-backend
 :name
 "preview"
 
 :candidate-filter
 (lambda (input)
   (when (and (> (length input) 4) (string-match "-" input))
     (let* ((tag (upcase (car (split-string input "-"))))
            (num (cadr (split-string input "-")))
            (num-0 (concat "00" num))
            candidates)
       (when-let ((pair (assoc tag jav-preview-alist))) 
         (when (> (length num) 1)
           (if-let* ((prefix (cdr (assoc tag jav-preview-prefix-alist)))
                     (prefix-num (concat prefix num)))
               (snails-add-candiate 'candidates
                                    (concat tag "-" prefix-num)
                                    (format (cdr pair) prefix-num prefix-num))             
             (snails-add-candiate 'candidates (concat tag "-" num) (format (cdr pair) num num))
             (snails-add-candiate 'candidates
                                  (concat tag "-" num-0)
                                  (format (cdr pair) num-0 num-0))
             )
           (snails-sort-candidates input candidates 0 0)
           candidates
           )
         )
       )
     )
   )

 :candidate-icon
 (lambda (candidate)
   (snails-render-file-icon candidate))


 :candidate-do
 (lambda (candidate)
   (browse-url  (s-trim candidate))))

(setq jav-preview-prefix-alist
  '(
    ("DASD" . "00")
    ("MIZD" . "00")
    ("MMUS" . "00")
    ("IPX" . "00")
    ("SSIS" . "00")
    ("MGMQ" . "")
    ("DORI" . "")
    ("MVSD" . "00")
    ("MIDE" . "00")
    ("PPPD" . "00")
    ("SKMJ" . "")
    ))

(setq jav-preview-alist
  '(
    ("ABP" . "https://cc3001.dmm.co.jp/litevideo/freepv/1/118/118abp%s/118abp%s_dmb_w.mp4")
    ("ABW" . "https://cc3001.dmm.co.jp/litevideo/freepv/1/118/118abw%s/118abw%s_mhb_w.mp4")
    ("DORI" . "https://awscc3001.r18.com/litevideo/freepv/h/h_4/h_491dori%s/h_491dori%s_dmb_w.mp4")
    ("MMUS" . "https://awscc3001.r18.com/litevideo/freepv/m/mmu/mmus%s/mmus%s_dmb_w.mp4")
    ("MGMQ" . "https://awscc3001.r18.com/litevideo/freepv/m/mgm/mgmq%s/mgmq%s_dmb_w.mp4")
    ("ABS" . "https://cc3001.dmm.co.jp/litevideo/freepv/1/118/118abs%s/118abs%s_dmb_w.mp4")
    ("ADN" . "https://cc3001.dmm.co.jp/litevideo/freepv/a/adn%s/adn%s_dmb_w.mp4")
    ("AIDA" . "https://cc3001.dmm.co.jp/litevideo/freepv/h/h_4/h_491aida%s/h_491aida%s_mhb_w.mp4")
    ("AP" . "https://cc3001.dmm.co.jp/litevideo/freepv/n/n_1/n_1428ap%s/n_1428ap%s_dmb_w.mp4")
    ("APNS" . "https://cc3001.dmm.co.jp/litevideo/freepv/a/apn/apns%s/apns%s_mhb_w.mp4")
    ("ASD" . "https://cc3001.dmm.co.jp/litevideo/freepv/2/24a/24asd%s/24asd%s_mhb_w.mp4")
    ("ATID" . "https://cc3001.dmm.co.jp/litevideo/freepv/a/ati/atid%s/atid%s_dmb_w.mp4")
    ("AUKG" . "https://cc3001.dmm.co.jp/litevideo/freepv/a/auk/aukg%s/aukg%s_mhb_w.mp4")
    ("AVSA" . "https://cc3001.dmm.co.jp/litevideo/freepv/a/avs/avsa%s/avsa%s_dmb_w.mp4")
    ("BAB" . "https://cc3001.dmm.co.jp/litevideo/freepv/b/bab%s/bab%s_mhb_w.mp4")
    ("BAC" . "https://cc3001.dmm.co.jp/litevideo/freepv/b/bac%s/bac%s_mhb_w.mp4")
    ("BAHP" . "https://cc3001.dmm.co.jp/litevideo/freepv/b/bah/bahp%s/bahp%s_mhb_w.mp4")
    ("BBAN" . "https://cc3001.dmm.co.jp/litevideo/freepv/b/bba/bban%s/bban%s_mhb_w.mp4")
    ("BDA" . "https://cc3001.dmm.co.jp/litevideo/freepv/b/bda%s/bda%s_mhb_w.mp4")
    ("BEITC" . "https://awscc3001.r18.com/litevideo/freepv/b/bei/beitc%s/beitc%s_dmb_w.mp4")
    ("BF" . "https://cc3001.dmm.co.jp/litevideo/freepv/b/bf%s/bf%s_mhb_w.mp4")
    ("BLK" . "https://cc3001.dmm.co.jp/litevideo/freepv/b/blk%s/blk%s_mhb_w.mp4")
    ("BLKW" . "https://cc3001.dmm.co.jp/litevideo/freepv/h/h_1/h_1437blkw%s/h_1437blkw%s_mhb_w.mp4")
    ("CAWD" . "https://cc3001.dmm.co.jp/litevideo/freepv/c/caw/cawd%s/cawd%s_mhb_w.mp4")
    ("CESD" . "https://cc3001.dmm.co.jp/litevideo/freepv/c/ces/cesd%s/cesd%s_dmb_w.mp4")
    ("COD" . "https://cc3001.dmm.co.jp/litevideo/freepv/2/24c/24cod%s/24cod%s_mhb_w.mp4")
    ("CPDE" . "https://cc3001.dmm.co.jp/litevideo/freepv/1/118/118cpde%s/118cpde%s_mhb_w.mp4")
    ("CSCT" . "https://cc3001.dmm.co.jp/litevideo/freepv/5/55c/55csct%s/55csct%s_mhb_w.mp4")
    ("DANDY" . "https://cc3001.dmm.co.jp/litevideo/freepv/1/1da/1dandy%s/1dandy%s_mhb_w.mp4")
    ("DVDMS" . "https://awscc3001.r18.com/litevideo/freepv/d/dvd/dvdms%s/dvdms%s_dmb_w.mp4")
    ("DASD" . "http://cc3001.dmm.co.jp/litevideo/freepv/d/das/dasd%s/dasd%s_dmb_w.mp4")
    ("DDOB" . "http://cc3001.dmm.co.jp/litevideo/freepv/d/ddo/ddob%s/ddob%s_dmb_w.mp4")
    ("DNJR" . "https://cc3001.dmm.co.jp/litevideo/freepv/d/dnj/dnjr%s/dnjr%s_mhb_w.mp4")
    ("DOKS" . "https://cc3001.dmm.co.jp/litevideo/freepv/h/h_1/h_139doks%s/h_139doks%s_mhb_w.mp4")
    ("DTT" . "http://cc3001.dmm.co.jp/litevideo/freepv/1/118/118dtt%s/118dtt%s_dmb_w.mp4")
    ("DVAJ" . "https://cc3001.dmm.co.jp/litevideo/freepv/d/dva/dvaj%s/dvaj%s_mhb_w.mp4")
    ("DPMX" . "https://awscc3001.r18.com/litevideo/freepv/d/dpm/dpmx%s/dpmx%s_dmb_w.mp4")
    ("EBOD" . "https://cc3001.dmm.co.jp/litevideo/freepv/e/ebo/ebod%s/ebod%s_dmb_w.mp4")
    ("ECB" . "https://cc3001.dmm.co.jp/litevideo/freepv/2/2ec/2ecb%s/2ecb%s_mhb_w.mp4")
    ("EKDV" . "https://cc3001.dmm.co.jp/litevideo/freepv/4/49e/49ekdv%s/49ekdv%s_mhb_w.mp4")
    ("EVIS" . "https://cc3001.dmm.co.jp/litevideo/freepv/e/evi/evis%s/evis%s_mhb_w.mp4")
    ("FNEO" . "https://cc3001.dmm.co.jp/litevideo/freepv/h/h_4/h_491fneo%s/h_491fneo%s_mhb_w.mp4")
    ("FSDSS" . "https://cc3001.dmm.co.jp/litevideo/freepv/1/1fs/1fsdss%s/1fsdss%s_dmb_w.mp4")
    ("GEKI" . "https://cc3001.dmm.co.jp/litevideo/freepv/g/gek/geki%s/geki%s_dmb_w.mp4")
    ("GUN" . "https://cc3001.dmm.co.jp/litevideo/freepv/4/433/433gun%s/433gun%s_mhb_w.mp4")
    ("GVH" . "https://cc3001.dmm.co.jp/litevideo/freepv/1/13g/13gvh%s/13gvh%s_dmb_w.mp4")
    ("GVG" . "http://cc3001.dmm.co.jp/litevideo/freepv/1/13g/13gvg%s/13gvg%s_dmb_w.mp4")
    ("HBAD" . "https://cc3001.dmm.co.jp/litevideo/freepv/1/1hb/1hbad%s/1hbad%s_mhb_w.mp4")
    ("HND" . "https://cc3001.dmm.co.jp/litevideo/freepv/h/hnd%s/hnd%s_mhb_w.mp4")
    ("HNDS" . "https://cc3001.dmm.co.jp/litevideo/freepv/h/hnd/hnds%s/hnds%s_mhb_w.mp4")
    ("HOMA" . "https://cc3001.dmm.co.jp/litevideo/freepv/h/hom/homa%s/homa%s_mhb_w.mp4")
    ("HONB" . "https://cc3001.dmm.co.jp/litevideo/freepv/h/h_1/h_1133honb%s/h_1133honb%s_mhb_w.mp4")
    ("HUNTA" . "https://cc3001.dmm.co.jp/litevideo/freepv/h/hun/hunta%s/hunta%s_mhb_w.mp4")
    ("HZGD" . "http://cc3001.dmm.co.jp/litevideo/freepv/h/h_1/h_1100hzgd%s/h_1100hzgd%s_mhb_w.mp4")
    ("IDBD" . "http://cc3001.dmm.co.jp/litevideo/freepv/i/idb/idbd%s/idbd%s_dm_w.mp4")
    ("IENF" . "https://cc3001.dmm.co.jp/litevideo/freepv/1/1ie/1ienf%s/1ienf%s_mhb_w.mp4")
    ("IPX" . "https://awscc3001.r18.com/litevideo/freepv/i/ipx/ipx%s/ipx%s_dmb_w.mp4")
    ("IPZ" . "https://cc3001.dmm.co.jp/litevideo/freepv/i/ipz%s/ipz%s_dmb_w.mp4")
    ("JBD" . " http://cc3001.dmm.co.jp/litevideo/freepv/j/jbd%s/jbd%s_dmb_w.mp4")
    ("JUL" . "https://cc3001.dmm.co.jp/litevideo/freepv/j/jul%s/jul%s_dmb_w.mp4")
    ("JUY" . " https://cc3001.dmm.co.jp/litevideo/freepv/j/juy%s/juy%s_dmb_w.mp4")
    ("JUFD" . " http://awspv3001.r18.com/litevideo/freepv/j/juf/jufd%s/jufd%s_dmb_w.mp4")
    ("JUFE" . "https://cc3001.dmm.co.jp/litevideo/freepv/j/juf/jufe%s/jufe%s_mhb_w.mp4")
    ("KAWD" . "https://cc3001.dmm.co.jp/litevideo/freepv/k/kaw/kawd%s/kawd%s_dmb_w.mp4")
    ("KTB" . "https://cc3001.dmm.co.jp/litevideo/freepv/k/ktb%s/ktb%s_dmb_w.mp4")
    ("KTKL" . "https://cc3001.dmm.co.jp/litevideo/freepv/k/ktk/ktkl%s/ktkl%s_mhb_w.mp4")
    ("KTRA" . "https://cc3001.dmm.co.jp/litevideo/freepv/h/h_0/h_094ktra%s/h_094ktra%s_mhb_w.mp4")
    ("LULU" . "https://cc3001.dmm.co.jp/litevideo/freepv/l/lul/lulu%s/lulu%s_mhb_w.mp4")
    ("LZPL" . "https://cc3001.dmm.co.jp/litevideo/freepv/l/lzp/lzpl%s/lzpl%s_mhb_w.mp4")
    ("KNMB" . "https://awscc3001.r18.com/litevideo/freepv/h/h_4/h_491knmb%s/h_491knmb%s_dmb_w.mp4")
    ("MEYD" . " https://cc3001.dmm.co.jp/litevideo/freepv/m/mey/meyd%s/meyd%s_dmb_w.mp4")
    ("MGMJ" . "https://cc3001.dmm.co.jp/litevideo/freepv/m/mgm/mgmj%s/mgmj%s_mhb_w.mp4")
    ("MIAA" . "https://cc3001.dmm.co.jp/litevideo/freepv/m/mia/miaa%s/miaa%s_dmb_w.mp4")
    ("MIAD" . "https://cc3001.dmm.co.jp/litevideo/freepv/m/mia/miad%s/miad%s_dmb_w.mp4")
    ("MIAE" . " https://cc3001.dmm.co.jp/litevideo/freepv/m/mia/miae%s/miae%s_dmb_w.mp4")
    ("MIDE" . " https://cc3001.dmm.co.jp/litevideo/freepv/m/mid/mide%s/mide%s_dmb_w.mp4")
    ("MIFD" . "https://cc3001.dmm.co.jp/litevideo/freepv/m/mif/mifd%s/mifd%s_mhb_w.mp4")
    ("MILK" . "https://cc3001.dmm.co.jp/litevideo/freepv/h/h_1/h_1240milk%s/h_1240milk%s_mhb_w.mp4")
    ("MIMK" . "http://cc3001.dmm.co.jp/litevideo/freepv/m/mim/mimk%s/mimk%s_mhb_w.mp4")
    ("MIRD" . "https://cc3001.dmm.co.jp/litevideo/freepv/m/mir/mird%s/mird%s_dmb_w.mp4")
    ("MISM" . "https://cc3001.dmm.co.jp/litevideo/freepv/m/mis/mism%s/mism%s_dmb_w.mp4")
    ("MIZD" . "https://cc3001.dmm.co.jp/litevideo/freepv/m/miz/mizd%s/mizd%s_dmb_w.mp4")
    ("MKMP" . "https://cc3001.dmm.co.jp/litevideo/freepv/8/84m/84mkmp%s/84mkmp%s_mhb_w.mp4")
    ("MSFH" . "https://cc3001.dmm.co.jp/litevideo/freepv/1/1ms/1msfh%s/1msfh%s_dmb_w.mp4")
    ("MVSD" . "https://awscc3001.r18.com/litevideo/freepv/m/mvs/mvsd%s/mvsd%s_dmb_w.mp4")
    ("MUDR" . " https://cc3001.dmm.co.jp/litevideo/freepv/m/mud/mudr%s/mudr%s_dmb_w.mp4")
    ("NEO" . "https://cc3001.dmm.co.jp/litevideo/freepv/4/433/433neo%s/433neo%s_mhb_w.mp4")
    ("NHDTA" . "http://cc3001.dmm.co.jp/litevideo/freepv/1/1nh/1nhdta%s/1nhdta%s_dmb_w.mp4")
    ("NITR" . "https://awscc3001.r18.com/litevideo/freepv/4/49n/49nitr%s/49nitr%s_dmb_w.mp4")
    ("OAE" . "https://cc3001.dmm.co.jp/litevideo/freepv/o/oae%s/oae%s_mhb_w.mp4")
    ("OMT" . "https://cc3001.dmm.co.jp/litevideo/freepv/h/h_1/h_1359omt%s/h_1359omt%s_mhb_w.mp4")
    ("PIYO" . "https://cc3001.dmm.co.jp/litevideo/freepv/1/1pi/1piyo%s/1piyo%s_mhb_w.mp4")
    ("PKPD" . "https://cc3001.dmm.co.jp/litevideo/freepv/p/pkp/pkpd%s/pkpd%s_mhb_w.mp4")
    ("PPPD" . " https://cc3001.dmm.co.jp/litevideo/freepv/p/ppp/pppd%s/pppd%s_dmb_w.mp4")
    ("PRED" . " https://cc3001.dmm.co.jp/litevideo/freepv/p/pre/pred%s/pred%s_dmb_w.mp4")
    ("PRTD" . "https://cc3001.dmm.co.jp/litevideo/freepv/p/prt/prtd%s/prtd%s_mhb_w.mp4")
    ("RBD" . " https://cc3001.dmm.co.jp/litevideo/freepv/r/rbd%s/rbd%s_dmb_w.mp4")
    ("REBD" . " https://cc3001.dmm.co.jp/litevideo/freepv/n/n_1/n_1412rebd%s/n_1412rebd%s_dmb_w.mp4")
    ("ROOM" . "https://cc3001.dmm.co.jp/litevideo/freepv/r/roo/room%s/room%s_mhb_w.mp4")
    ("SALO" . "https://cc3001.dmm.co.jp/litevideo/freepv/8/84s/84salo%s/84salo%s_mhb_w.mp4")
    ("SDAB" . "https://cc3001.dmm.co.jp/litevideo/freepv/1/1sd/1sdab%s/1sdab%s_mhb_w.mp4")
    ("SDDE" . "https://cc3001.dmm.co.jp/litevideo/freepv/1/1sd/1sdde%s/1sdde%s_dmb_w.mp4")
    ("SDJS" . "https://cc3001.dmm.co.jp/litevideo/freepv/1/1sd/1sdjs%s/1sdjs%s_mhb_w.mp4")
    ("SDNM" . "https://cc3001.dmm.co.jp/litevideo/freepv/1/1sd/1sdnm%s/1sdnm%s_mhb_w.mp4")
    ("SHKD" . " http://awspv3001.r18.com/litevideo/freepv/s/shk/shkd%s/shkd%s_dmb_w.mp4")
    ("SNIS" . "https://cc3001.dmm.co.jp/litevideo/freepv/s/sni/snis%s/snis%s_dmb_w.mp4")
    ("SOJU" . "https://cc3001.dmm.co.jp/litevideo/freepv/s/soj/soju%s/soju%s_mhb_w.mp4")
    ("SQTE" . "https://cc3001.dmm.co.jp/litevideo/freepv/s/sqt/sqte%s/sqte%s_mhb_w.mp4")
    ("SKMJ" . "https://awscc3001.r18.com/litevideo/freepv/h/h_1/h_1324skmj%s/h_1324skmj%s_dmb_w.mp4")
    ("SSNI" . " https://cc3001.dmm.co.jp/litevideo/freepv/s/ssn/ssni%s/ssni%s_dmb_w.mp4")
    ("SSIS" . "https://awscc3001.r18.com/litevideo/freepv/s/ssi/ssis%s/ssis%s_dmb_w.mp4")
    ("STAR" . "http://dl.sod.co.jp/201810/star%s/star%s_288_sample.mp4")
    ("STARS" . "http://cc3001.dmm.co.jp/litevideo/freepv/1/1st/1stars%s/1stars%s_sm_w.mp4")
    ("T" . "ht%s//cc3001.dmm.co.jp/lit%s_mhb_w.mp4")
    ("URE" . " https://cc3001.dmm.co.jp/litevideo/freepv/u/ure%s/ure%s_dmb_w.mp4")
    ("VENU" . "https://cc3001.dmm.co.jp/litevideo/freepv/v/ven/venu%s/venu%s_mhb_w.mp4")
    ("VRTM" . "https://cc3001.dmm.co.jp/litevideo/freepv/h/h_9/h_910vrtm%s/h_910vrtm%s_mhb_w.mp4")
    ("WANZ" . " https://cc3001.dmm.co.jp/litevideo/freepv/w/wan/wanz%s/wanz%s_dmb_w.mp4")
    ("XMOM" . "https://cc3001.dmm.co.jp/litevideo/freepv/h/h_0/h_086xmom%s/h_086xmom%s_mhb_w.mp4")
    ("XRW" . "https://cc3001.dmm.co.jp/litevideo/freepv/8/84x/84xrw%s/84xrw%s_mhb_w.mp4")
    ("XVSR" . "https://cc3001.dmm.co.jp/litevideo/freepv/x/xvs/xvsr%s/xvsr%s_dmb_w.mp4")
    ("YMDD" . "https://awscc3001.r18.com/litevideo/freepv/y/ymd/ymdd%s/ymdd%s_dmb_w.mp4")
    ("YTR" . "https://awscc3001.r18.com/litevideo/freepv/h/h_1/h_127ytr%s/h_127ytr%s_dmb_w.mp4")
    ("ZEX" . "https://cc3001.dmm.co.jp/litevideo/freepv/h/h_7/h_720zex%s/h_720zex%s_mhb_w.mp4")
    ("ZMEN" . "https://cc3001.dmm.co.jp/litevideo/freepv/h/h_1/h_1371zmen%s/h_1371zmen%s_dmb_w.mp4")
    ("NHTDB" . "http://cc3001.dmm.co.jp/litevideo/freepv/1/1nh/1nhtdb%s/1nhtdb%s_dmb_w.mp4")
    )
  )

(provide 'snails-backend-preview)
