- name: openai/o3-mini
  edit_format: diff
  weak_model_name: deepseek/deepseek-coder
  use_repo_map: true
  use_temperature: false
  editor_model_name: deepseek/deepseek-coder
  editor_edit_format: editor-diff
  reminder: sys
  examples_as_sys_msg: true
  caches_by_default: true
